# File name of io.yaml file, which should exist in the directory from which you
# call com functions
io_config: io.yaml

# batch_size*{num_cameras} should be <= 6 for most COM training applications
batch_size: 6

# Degree of downsampling applied to image input. The demo COMfinder was trained
# with downfac:2, but when fine-tuning your own COMfinder, we suggest using 
# 4, which will greatly increase prediction speed. This of course depends on the
# size of your raw images. If they are low resolution to begin with, you won't
# need or want to use a large downfac value.
downfac: 4

# Learning rate for the Adam optimizer. Default 5e-5.
lr: 5e-5

# How many samples from each animal do you want to (randomly) set aside for a validation metric?
num_validation_per_exp: 4
net: unet2d_fullIN

# If true, saves plots of the training labels overlaid on images
#debug: False

# If present, write the confidence map output and image/COM overlays to disk during prediction
#COMdebug: Camera5

# How many frames to you want to predict over? Set to 'max' for all video frames.
max_num_samples: 'max'

#com_finetune_weights: ./COM/weights/

mono: True

mirror: True

debug: True

epochs: 1000
